version: '2'

services:
   tx:
     build: .
     hostname: tx
     environment:
       ROLE: tx
       DESTINATION: rx
       MIN_MTU: 1450
       MAX_MTU: 1600
     depends_on:
       - rx

   rx:
     build: .
     hostname: rx
     ports:
       - 5001:5001
     environment:
       ROLE: rx
       L4P: TCP

